### ISSUE TITLE
Kunden Logos anpassen

### ISSUE THREAD

**Issue by wirebug** [kreinn/ub-burzlaff#19]
Es sollten Partner-Logos in besserer Auflösung vorliegen und uU eine alternative Darstellung gewählt werden.
- [x] NRW KPV
- [x] SG Suderwich
- [x] Handwerkskammer Köln
- [x] hessen Tischler
- [x] Stadt Dortmund
- [ ] Zukunftsinitative handwerk NRW: http://www.handwerk.nrw/ ?
- [x] DeceTe
- [x] Verkehrsverein Kevelaer und Umbegung ev
- [x] Wy^zsza Szkola Handlowa Handlowa.eu
- [ ] GIB
- [x] Abse Stys , http://www.abse-stys.de/
- [ ] QSN Qulitätsgemeinschaft Sicherheit Nord
- [ ] Handwerkskammer Dortmund
- [ ] Fachhochschule Dortmund
- [ ] ifkb Rh bmbg
- [ ] typisch landkreis vechta
- [ ] smf ihr partner
- [ ] Die Führungskräfte
- [ ] tischler nrw

**Comment by silasmahler** [comment]
@wirebug Nach dem Gespräch mit Norbert siehe #31

**Comment by silasmahler** [comment]
@wirebug Merkarion soll laut Norbert nicht aus dem alten Kundenkreis übernommen werden, dafür gerne Elektro-Günther

**Comment by silasmahler** [comment]
Die Kundenlogos passen wir in Release 1.1 an
