### ISSUE TITLE
Texte von alter HP einfügen ( und Unterseiten für Seminarangebote)

### ISSUE THREAD

**Issue by silasmahler** [kreinn/ub-burzlaff#2]

**Comment by jo2** [comment]
wie soll das gemacht werden? unterseiten? mit panels wo jeweils 1 aktiviert ist und man da den inhalt sehen kann so wie im "warum wir?" von der kreinn seite?

**Comment by silasmahler** [comment]
@jo2 Es reichen beim Punkt Bewertungen ein paar Beispiele und moderne Fotos, Norbert wollte eh weniger Text

**Comment by jo2** [comment]
wie soll das denn umgesetzt werden?

**Comment by silasmahler** [comment]
Einfach Fotos, die man kommerziell verwenden darf raussuchen und das was passt aus den alten seminaren mitnehmen an texten, aber nicht sonderlich viel

**Comment by jo2** [comment]
sollen die Informationen da als unterseiten rein oder als panel wie bei "warum wir?" von der kreinn seite? Außerdem sollten wir da kein stock material verwenden, weil norbert ja bei uns beratung macht und seminare wo norbert nicht dabei ist ist dann nicht seriös

**Comment by silasmahler** [comment]
@jo2 ja für den anfang reicht stockmaterial, danach soll das nach und nach ergänzt werden, ja da reichen klleine panels, später wenn mehr hochauflösende bilder vorhanden sind, kann man auch über eine unterseite nachdenken

**Comment by silasmahler** [comment]
#14

**Comment by jo2** [comment]
@silasmahler kümmerst du dich dann mit norbert um das stcokmaterial?

**Comment by silasmahler** [comment]
@jo2 ja ich hab mit norbert geredet wir ergänzen das später und nehmen erstmal den menupunkt raus. Wenn wir etwas haben, dann ergänzen wir das
