### ISSUE TITLE
Margin in tablet mode zu gering

### ISSUE THREAD

**Issue by silasmahler** [kreinn/ub-burzlaff#37]
![grafik](https://user-images.githubusercontent.com/14834495/38216991-de1a063c-36cc-11e8-9812-1048a2f7a9dc.png)

**Comment by silasmahler** [comment]
Kann auch im weiteren Release, ich kümmer mich erstmal um die aktuelle Auslieferung

**Comment by jo2** [comment]
@wirebug hast du da schon was dran gemacht? sonst mache ich das ich hab das ja so fabriziert
