### ISSUE TITLE
Workshops

### ISSUE THREAD

**Issue by jo2** [kreinn/ub-burzlaff#44]
Überschrift: Wir führen Workshops zu vorher definierten Themen durch.
Techniken:
- Kreativitätstechniken
- Metaplan
Methoden:
- Vortrag
- Interaktive Beiträge der Teilnehmer/innen
- Gruppenarbeit
- Fallbeispiele
- Disskusionen

**Comment by silasmahler** [comment]
Das mal bitte ins Pad

**Comment by jo2** [comment]
das soll noch auf die seite

**Comment by silasmahler** [comment]
Alles klar
