### ISSUE TITLE
Telefon link funktioniert nicht

### ISSUE THREAD

**Issue by jo2** [kreinn/ub-burzlaff#46]

**Comment by jo2** [comment]
Bei Smartphones und unter Windows kann man mit einem link mit a href="tel:.." einen Anruf über die Standard-Telefonapp ausführen. Unter Linux geht dies nicht. Wie sollen wir das dann machen? Ich denke, dass die meisten die die Seite besuchen ein Windows-Gerät oder Smartphone nutzen.

**Comment by wirebug** [comment]
rel="nofollow" bringt nichts
![screenshot from 2018-05-03 10 38 30](https://user-images.githubusercontent.com/11160119/39567247-a4feb122-4ebe-11e8-9c1b-7c1297275b99.png)

**Comment by wirebug** [comment]
Bei mir geht es immer noch nicht. -> Nur weil es bei dir geht... :pensive:

**Comment by silasmahler** [comment]
@wirebug Check mal deine Plugins, hatten das hier mit mehreren Leuten kurz getestet und es hatte in verschiedenen Browsern funktioniert

**Comment by jo2** [comment]
@silasmahler das liegt linux. es wäre mal interessant das mit nem mac os zu testen. wenn das dann für 1/4 der leute nicht geht ist das nicht gut
